// Generated by CoffeeScript 1.10.0
var AlchemyManager, HttpStatus, TwitterManager, WishboneManager;

HttpStatus = require('http-status');

WishboneManager = require('../managers/WishboneManager');

AlchemyManager = require('../managers/AlchemyManager');

TwitterManager = require('../managers/TwitterManager');

module.exports = function(app, router) {

  /*Add device to user's profile api */
  return router.post('/status', function(req, res, next) {
    return WishboneManager.getPosts(function(posts) {
      if (posts) {
        return AlchemyManager.getResult(posts, function(response) {
          console.log(response);
          return response.forEach(function(user, key) {
            return TwitterManager.postStatus(user.screen_name, user.message, function(finalResponse) {
              if (response.length === key + 1) {
                return res.status(HttpStatus.OK).json("success");
              }
            });
          });
        });
      } else {
        return res.status(HttpStatus.NO_CONTENT).send();
      }
    });
  });
};
