// Generated by CoffeeScript 1.10.0
var PORT, app, bodyParser, db, express, expressValidator, models, router;

express = require('express');

models = require('./models');

bodyParser = require('body-parser');

db = require('./models/index');

expressValidator = require('express-validator');

app = express();

router = express.Router();

PORT = process.env.PORT || 5000;

app.use(bodyParser.urlencoded({
  extended: false
}));

app.use(expressValidator());

app.set('view engine', 'hbs');

app.set('views', __dirname + '/views');

app.set('port', process.env.PORT || PORT);


/*models.sequelize.sync({ logging: console.log }).then ->
 console.log ('model synced')
 return
 */

app.use(require('./routes'));

app.get('/', function(req, res) {
  res.send('Hello World!!');
});

app.listen(PORT, function() {
  console.log('Example app listening on port ' + PORT);
});

app.use(function(req, res, next) {
  var err;
  err = new Error('Not Found');
  err.status = 404;
  next(err);
});

app.use(function(err, req, res, next) {
  res.status(err.status || 500);
  res.render('error', {
    message: err.message,
    error: app.get('env') === 'development' ? err : {}
  });
});
